src/objects/CityManager__c.object
<CustomObject>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CityManager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CityManager</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CityManagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>CityManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CityManager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan</relationshipLabel>
        <relationshipName>Loan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PopulateManagerOfLoanTriggerController.cls
public class PopulateManagerOfLoanTriggerController {
	public static List<Loan__c> loanList {get;set;}
	public static void setManagerOfLoan() {
		map<String,Id> cityManagerMap= new map<String,Id>();
		for(CityManager__c tempCityManager : [Select c.Name, c.Manager__c From CityManager__c c ]){
			cityManagerMap.put(tempCityManager.Name,tempCityManager.Manager__c);
		}
		for(Loan__c tempLoan :loanList){
			if(tempLoan.City__c != null){
				tempLoan.CityManager__c = cityManagerMap.get(tempLoan.City__c);
			}
		}
	}
}