src/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>YEAR( TODAY() ) -  YEAR( DOB__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>email__c</fullName>
        <label>email</label>
        <type>Email</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StudentDetailPdfController.cls
public class StudentDetailPdfController {
    public Student__c student{get;set;}
    private String sid;
    
    public StudentDetailPdfController(){
        try{
           sid = ApexPages.currentPage().getParameters().get('id');
           if(sid != null) {               
               List<Student__c> studentList = [Select s.Name, s.First_Name__c, s.Last_Name__c, s.Sex__c , s.Class__r.Name,s.DOB__c,s.Age__c,s.email__c From Student__c s where s.Id = : sid limit 1];  
               if(studentList.size() > 0) {
                   student = studentList[0];
                   //system.assert(false, student);
               } else {
                   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No such record exists'));
               }
           } else {
               ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid parameter passed'));
           }
        } catch(Exception e){   
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));           
        }        
    }
        
    public pageReference renderAsPdf(){                       
          PageReference PR = Page.Studentpdf;           
          Blob pdf = PR.getcontentasPDF();                                                        
          List <Attachment> Existingattachmt=[select a.Name,a.ParentID from Attachment a where a.ParentID=:student.Id];       
          Attachment attach=new Attachment();                                
          attach.Body=pdf;
          attach.Name='Student:..'+ student.Name+'--'+system.now()+'.pdf';
          attach.ParentID=student.Id;
          if(!(Existingattachmt.isEmpty())){
                  delete Existingattachmt;
          }
          try {
              insert(attach);                             
          }
          catch(System.DMLException e){
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage()));
              return null;
          }
          return new ApexPages.StandardController(student).view();
     }
}