src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class</pluralLabel>
    <recordTypes>
        <fullName>Test</fullName>
        <active>true</active>
        <label>Test</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <picklist>
            <picklistValues>
                <fullName>Hindi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maths</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Science</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Custom_Status__c</fullName>
        <label>Custom Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestTriggers.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestTriggers {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
         Class__c classobj=new Class__c(Name__c='X1',Name='X1',MyCount__c=2);
         insert classobj;
         Student__c testStudent1 = new Student__c(Last_Name__c='bagaria',Class__c=classobj.Id);
         Student__c testStudent2 = new Student__c(Last_Name__c='gupta',Class__c=classobj.Id);
         Student__c testStudent3 = new Student__c(Last_Name__c='agarwal',Class__c=classobj.Id);
         insert testStudent1;
         insert testStudent2;
         try{
         	insert testStudent3;
         }
         catch(DMLException e){
        	
        }
        
        Opportunity op = new Opportunity(Name='op11',CloseDate=Date.Parse('12/12/2014'),StageName='Qualification',Custom_Status__c='New');
        insert op;
        op.StageName = 'Closed Won';
        try{
        	update op;
        }
        catch(DMLException e){
        	
        }
        Opportunity op1 = new Opportunity(Name='op11',CloseDate=Date.Parse('12/12/2014'),StageName='Qualification',Custom_Status__c='Reset');
     //   op.Custom_Status__c='Reset';
        try{
        	update op1;
        }
        catch(DMLException e){
        	
        }
        try{
        	delete classobj;
        }
        catch(DMLException e){
        	
        }
        Contact teacher = new Contact(LastName = 'sharma',Subjects__c = 'hindi');
        try{
       	 insert teacher;
        }
        catch(DMLException e){
        	
        }
    }
}