src/objects/Products__c.object
<CustomObject>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Products</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Date__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Purchase_Order_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_ID__c</fullName>
        <label>Product ID</label>
        <referenceTo>Products__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order_ID__c</fullName>
        <label>Purchase Order ID</label>
        <referenceTo>Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Line Items</relationshipLabel>
        <relationshipName>Purchase_Order_Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalItemPrice__c</fullName>
        <formula>Quantity__c  *  Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalItemPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line Item</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderDetailController.cls
public class OrderDetailController {
	private String purchaseOrderId;
	
	public Decimal totalPrice{get;set;}
	
	public List<Purchase_Order_Line_Item__c> orderedLineItemList{get;set;}
	
    public OrderDetailController(ApexPages.StandardController controller) {
		purchaseOrderId=ApexPages.currentPage().getParameters().get('Id');
		if(purchaseOrderId != null){
			totalPrice=0;
			orderedLineItemList=[Select p.Quantity__c,p.Total_Price__c, p.Product_ID__r.Product_Name__c, p.Name,p.TotalItemPrice__c,p.Unit_Price__c From Purchase_Order_Line_Item__c p  where p.Purchase_Order_ID__c =:purchaseOrderId];
			for(Purchase_Order_Line_Item__c temporderedItem :orderedLineItemList){
				totalPrice=totalPrice+temporderedItem.TotalItemPrice__c;
			}
		}else{
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Please First select Items For Order'));
		}	
    }
    public void updateStatus(){
    	Purchase_Order__c purchaseOrder=[Select p.Status__c,p.Total_Price__c,Purchase_Date__c From Purchase_Order__c p where p.Id =: purchaseOrderId limit 1];
			purchaseOrder.Status__c='Delivered';
			purchaseOrder.Total_Price__c=totalPrice;
			purchaseOrder.Purchase_Date__c=system.today();
			try{
				update purchaseOrder;
			}
			catch(DMLException e){
				 ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, 'Unable to update Status'+e.getMessage()));
			}
    }
    public PageReference newOrderRedirect(){
    	return new PageReference('/a04/e?retURL=%2Fa04%2Fo');
    }
	
}